# Generated by Django 3.0.5 on 2020-04-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navprayas', '0002_auto_20200322_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('video', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
