# Generated by Django 3.0.5 on 2020-04-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navprayas', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='media/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
