# Generated by Django 3.0.5 on 2020-04-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navprayas', '0004_auto_20200407_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='media/navprayas/%Y/%m/%d/'),
        ),
    ]
